name: pages-build-deploy

on:
  # Trigger the deploy on push to main branch
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

jobs: 
 
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup python
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build book
      run: |
        jupyter-book build .

    - name: Push html to github-pages        
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        force_orphan: true

